### ISSUE TITLE
X-Forwarded-For header is incorrect

### ISSUE THREAD

**Issue by kristjanbjarni** [chmouel/gosmee#135]
X-Forwarded-For header is added to the outgoing request as expected, but it includes the port number, for example:

X-Forwarded-For: 127.0.0.1:1234

This is incorrect according to the specification:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

and since this header is critical for security and spoofing many endpoints reject any invalid x-forwarded-for header in the request with "400 bad request" as expected.

**Comment by chmouel** [comment]
interesting, we only replay things as forwarded, but i think in this case you are right!

**Comment by jvieiraNE** [comment]
Hi,

Could this be related to the issue I am currently having?

Trying to connect Gosmee to Jenkins, but the logs say:

```
Wed, 19 Jun 2024 12:19:23 UTC INF Starting gosmee version: dev

Wed, 19 Jun 2024 12:19:23 UTC INF 2024-06-19T12.19.06.916 Forwarding https://smee.io/JmSqJ36FoDOumMYZ to http://192.168.50.32:8075/github-webhook/

Wed, 19 Jun 2024 12:19:50 UTC INF 2024-06-19T12.19.06.985 56-xxxxxx-9f1b4 push event replayed to http://192.168.50.32:8075/github-webhook/, status: 400, error: 400 Bad Request
```

I am assuming that the issue lies with Gosmee.

**Comment by kristjanbjarni** [comment]
> I am assuming that the issue lies with Gosmee.

Yes looks likely. It seems gosmee is currently unusable with any endpoint software that has strict compliancy with the de-facto HTTP specification.

**Comment by chmouel** [comment]
seems like smee.io is the one sending it, we don't do this when using gosmee server (as run by caddy in front)

I have issues a quick fix to remove them and will issue a minor release

**Comment by chmouel** [comment]
Fix is available now in https://github.com/chmouel/gosmee/releases/tag/v0.22.1 let me know if this works for you

**Comment by jvieiraNE** [comment]
Worked perfectly! Thank you very much for your fast response.

**Comment by chmouel** [comment]
thanks to @kristjanbjarni for expalining the problem perfectly :)

**Comment by kristjanbjarni** [comment]
Thanks @chmouel for your work.
