### ISSUE TITLE
Connection reset when using server

### ISSUE THREAD

**Issue by kgosciniak-insys** [chmouel/gosmee#142]
OS: Windows 11 23H2
Docker version: Docker version 24.0.7

When running 
```
docker run -p 3333:3333 ghcr.io/chmouel/gosmee:latest server
```

I'm getting: 
```
Serving for webhooks on http://localhost:3333
```

But when trying to connect tho this URL I'm getting Connection reset error in browser, and while using curl empty response.
![Screenshot 2024-04-03 114138](https://github.com/chmouel/gosmee/assets/19572318/f6f79030-e4ae-4acd-b00a-72000c71334b)

Are there any necessary steps missing to fully utilize this functionality or there is some bug?

**Comment by kgosciniak-insys** [comment]
@chmouel can someone take a look at this?

**Comment by chmouel** [comment]
this sounds like a docker error to me...

**Comment by kgosciniak-insys** [comment]
> this sounds like a docker error to me...

@chmouel 
I've tried on multiple machines with linux/windows and different versions of app (tried latest, v21 v20). Can you provide example that works on your environment?

**Comment by kgosciniak-insys** [comment]
It seems like it works when using network mode host:
`docker run -d --restart always --network host --name ***** ghcr.io/chmouel/gosmee:latest server --port 3026 --address my.ip.address`

There seems to be issue when using bridged mode, probably because binding is explicit to localhost. Maybe change it to bind to all ip addresses? Also it would be nice to update the documentation.

**Comment by chmouel** [comment]
i think if you do --address 0.0.0.0 that would work isnt it? without having to use network host

**Comment by kgosciniak-insys** [comment]
> i think if you do --address 0.0.0.0 that would work isnt it? without having to use network host

@chmouel Thanks for suggestion.
It seems to be working. My current command:
`docker run -d -p 3026:3026 --restart always --name example.org ghcr.io/chmouel/gosmee:latest server --port 3026 --address 0.0.0.0 --public-url https://example.org`

It would be nice to update readme with this example command.
